services:

  pokemon:
    build: ./pokemon
    volumes:
      - ./pokemon/src:/usr/src/app/src
    depends_on:
      - user

  match:
    build: ./match
    volumes:
      - ./match/src:/usr/src/app/src
      - ./match/package.json:/usr/src/app/package.json
    depends_on:
      - user

  user:
    build: ./user

  proxy:
    image: nginx
    volumes:
      - ./proxy:/etc/nginx:ro           #En read-only 
    ports:
      - "80:80"
    depends_on:
      - user
      - pokemon
      - match